# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2e68ad05779fa072a453c11f5ec15ad891309d9bbb97c42521f26725e33aef062ae4f61d8a0ea94f35a4508ca080008d13a1eae25016c92a96fbfc4d69b4788

test:
  secret_key_base: 32f3d7a094e239dde80b8589085b363a383c6647a3d9cc7cd7051c9d152540a9e94c8cf04ef075957ee77db8e51c6834392006f8dad684bf8e7bdf18765c2682

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
